### ISSUE TITLE
Percent Encoding in URL Path

### ISSUE THREAD

**Issue by neurosaurus** [vapor/engine#95] opened 2017-02-01 19:05 UTC
I have an API with a URI like this:

`let uri = "http://vapor.com/api/users/P%2BXCW4asdfa%2FOljlkH90/image?size=small&color=blue"`

I then call:

`let result = drop.client.get(uri)`

Vapor then calls URIParser.parse(...) to decode the URI including the path:
https://github.com/vapor/engine/blob/master/Sources/URI/Parser/Parser.swift#L66

Unfortunately, Vapor will decode, then re-encode the ENTIRE path. 
In this case, when it decodes and re-encodes the path component (in Request.swift), `"P%2BXCW4asdfa%2FOljlkH90"` gets "malformed" and creates/interprets it as a new path component: `"P+XCW4asdfa/OljlkH90"`.

The correct solution is for Vapor to faithfully reproduce my original URL, but I think Vapor is trying to be "correct" and build a "model" of what my URL looks like. But it's not accommodating for percent encoding in the URL path.

**Comment by tannernelson** [comment] 2017-02-02 11:43
Seems like either:
A: Path stops being percent-decoded
B: We percent-encode path when serializing back out.

A seems correct but also seems like it could cause issues elsewhere. Any ideas @LoganWright?

**Comment by vzsg** [comment] 2017-02-02 11:51
I think the same overzealous URL decoding leads to https://github.com/vapor/vapor/issues/758 too.

**Comment by LoganWright** [comment] 2017-02-02 13:53
@neurosaurus @vzsg @tannernelson 

I think we're getting into really confusing territory for when to percent encode, and when to not percent encode. Some people really expect this stuff to happen and others don't. 

Would percent encoding the path when serializing back out fix the problem?

On option A. That seems reasonable to me, I'm curious what Foundation was doing, I think replicating that behavior is probably ideal

**Comment by LoganWright** [comment] 2017-02-02 13:55
fwiw, NSURL behaves the same way:

```swift
let url = URL(string: "http://vapor.com/api/users/P%2BXCW4asdfa%2FOljlkH90/image?size=small&color=blue")!
print(url.path) // /api/users/P+XCW4asdfa/OljlkH90/image
```

How do they get around this?

**Comment by tannernelson** [comment] 2017-02-02 14:52
If NSURL session behaves the same way then we should probably leave this as is. 

A somewhat hacky solution could be adding a property on the URI class to get access to the raw url that the URI was parsed from.

The correct solution would seem to be changing `url.path` to be `[String]` so that the slashes are unambiguous. Maybe we could do this in a non-breaking way by adding `pathArray` and having `path` be computed by combining the elements into a string with slashes.

**Comment by edjiang** [comment] 2017-02-02 18:44
@neurosaurus messaged me about this quite a bit since at first it seemed similar to #24 from the inset.

The problem seems to be when paths have stuff like `/test%2Fpath/` -- that gets sent to the server as `/test/path/` by Vapor/engine.

Looking around it seems server implementations disagree with how to handle the scenario. Some frameworks treat `%2F` as equivalent to `/`, but the problem is that some treat them differently.

I suggested that in the URL parser, we look for the special case of `%2F` in the path string, and replace it with `%252F` (escaping the percent sign), before Vapor decodes the URL into its internal form. 

I believe @neurosaurus is working on a PR with a fix =]

**Comment by BrettRToomey** [comment] 2017-05-03 10:45
The new HTTP parser and URI updates address this among other issues. Closing for now.

**Closed by BrettRToomey** 2017-05-03 10:45 UTC
Labels: bug
