### ISSUE TITLE
Sending email via SMTP causes Illegal Instruction when running in a Docker image

### ISSUE THREAD

**Issue by rtvanals** [vapor/engine#99] opened 2017-02-10 05:15 UTC
When running the vapor image in an Ubuntu 14.04 Docker image w/ the Swift 3.0.2 RELEASE toolchain, and error "Illegal Instruction" gets thrown when trying to create the SMTP client.  

`let client = try SMTPClient<TCPClientStream>.makeGmailClient()`

The packages installed in the Docker images are:
`build-essential wget clang-3.6 curl libedit-dev python2.7 python2.7-dev libicu52 rsync libxml2 git`

**Comment by LoganWright** [comment] 2017-02-10 10:12
@rtvanals are there any more debug logs or anything going on you might be aware of?

**Comment by vzsg** [comment] 2017-02-10 10:49
Can you build a minimal project to reproduce the crash? A main.swift, a Package.swift and a Dockerfile posted on Gist would be enough.

**Comment by rtvanals** [comment] 2017-02-11 05:34
@LoganWright @vzsg I set up a very simple Vapor project that just sends an email and then started adding packages that I was using and it seems there is an issue with the Vapor engine and Kitura together.  It works when I just have the Vapor engine installed but when I change my package file to have these dependencies, it breaks.

```
    .Package(url: "https://github.com/IBM-Swift/Kitura.git", majorVersion: 1, minor: 6),
    .Package(url: "https://github.com/vapor/engine.git", majorVersion: 1, minor: 3)
```

My main.swift file is just this:

```
import SMTP
import Transport

let credentials = SMTPCredentials(
  user: "myemailaddress@email.com",
  pass: "mypassword"
)

let from = EmailAddress(name: "Name",
                        address: "noreply@myapp.com")

let to = EmailAddress(name: "Test",
                      address: "myemailaddress@email.com")

let email = Email(
  from: from,
  to: to,
  subject: "Vapor SMTP - Simple",
  body: "Hello from Vapor SMTP 👋"
)

do {
  let client = try SMTPClient<TCPClientStream>.makeGmailClient()
  try client.send(email, using: credentials)
} catch (let error) {
  print("Mail Error: \(error)")
}
```

**Comment by vzsg** [comment] 2017-02-12 02:49
Thanks for the repro and the extra details. I managed to reproduce it myself – I had to install `libssl-dev` in the Docker image, but no big deal.

The stacktrace of the illegal instruction is available [here](https://gist.github.com/vzsg/6ec8ad0e1dc16e68920869604469b892), which points at an unexpected nil value coming from the [TLS module](https://github.com/vapor/tls/blob/master/Sources/TLS/Config.swift#L48), a call to the C function `tls_config_new()`.

From what I can see, it seems that you haven't experienced a crash without Kitura because there is an internal clash between Vapor's LibreSSL (self-compiled) and Kitura's OpenSSL (pulled in as a system module). The `tls_config_new()` function is defined in both, which seems to cause erratic behavior on Linux, even though it works on macOS.

I don't know if there's a way to evade this. My best guess would be to stick with one framework instead of mixing them.

What do you think, @LoganWright?

**Comment by LoganWright** [comment] 2017-02-13 09:59
@vzsg You are absolutely accurate about the current Kitura/Vapor Conflict. Unfortunately, we'll probably not swap out LibreSSL quite yet since we had some problems w/ OpenSSL we'd prefer not to revisit 😄 

With Security apis from the server side group, we'll likely be using the same internals, so Kitura/Vapor conflict will disappear.

**Comment by BrettRToomey** [comment] 2017-05-03 10:46
@LoganWright @vzsg This is fixed in Vapor 2.0, right?

**Comment by BrettRToomey** [comment] 2017-05-03 10:46
Fat fingers... Oops...

**Comment by tanner0101** [comment] 2017-05-04 15:41
This should be fixed. If not, feel free to re-open.

**Closed by tanner0101** 2017-05-04 15:41 UTC
